### ISSUE TITLE
RFC 24 should support integer ranges

### ISSUE THREAD

**Issue by anwarmamat** [cedar-policy/rfcs#29]
[Arithmetic overflow validation](https://github.com/cedar-policy/cedar/issues/63) will add integer ranges to the schema. For example:
```
"attributes": {
  "jobLevel": {
    "type": "Long",
      "min": 1,
       "max": 10
   }
}
```

[RFC13](https://github.com/cedar-policy/rfcs/pull/13) will add enum ranges. For example: 
```
  "attributes": {
    "color": {
      "type": "String",
      "enum" : ["red", "blue", "green"]
    }
}
```
The new schema syntax should support ranges and enums

**Comment by shaobo-he-aws** [comment]
Integer range annotation RFC is rejected. RFC 13 is likely to be rejected. So I closed this issue.
