### ISSUE TITLE
RFC 24 errata

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/rfcs#42]
I found two issues while implementing RFC 24.

1. We don't have a grammar for Cedar values, which can be referred as action attributes. I propose we remove action attribute from the grammar since it's not a stable feature of Cedar either.

2. Action parent ids should be `Path`s instead of `Name`s because they could refer to entities from another namespace.

**Comment by mwhicks1** [comment]
> I propose we remove action attribute from the grammar since it's not a stable feature of Cedar either.

Some aspects of the grammar were designed with action attributes in mind; I recall switching the way `appliesTo` was defined to accommodate the needed structure for attributes. Let's make sure we keep that so attributes are possible later.

**Comment by cdisselkoen** [comment]
> [action attributes is] not a stable feature of Cedar

Action attributes are supported (in stable) in Cedar-without-schema.  They are only unsupported in schemas.  Nonetheless that doesn't change the point here, that RFC 24 need not / should not support action attributes in its schema format.

I agree with Mike that we want to ensure action attributes are easy to add later.
