### ISSUE TITLE
Set cannot contain different Entity types

### ISSUE THREAD

**Issue by jeffsec-aws** [cedar-policy/rfcs#46]
While schema gives the following definition for `Set` data type:

> A collection of elements that can be of the same or different types. A set is constructed using bracket characters [ ] and separating the elements with commas. The following examples show a few sets.

This give the sense that multiple types can be store in a `Set`. While generally true, this does not support the sub use case of multiple entities.

While the following schema definition can allow an entity of type `Group` to have a `Set` type attribute of entity of type `User`:
```
[...],
"Group" : {
    "shape" : {
        "type" : "Record",
        "attributes": {
            "Admins": {
                "type": "Set",
                "element": {
                    "type": "Entity",
                    "name": "User"
                }
            }
        }
    }
},
"User" : {
    "shape" : {
        "type" : "Record",
        "attributes": {
            "Location": {
                "type": "String"
            }
        }
    }
},
[...]
```
There is no way for me to expand the entity of type `Group` to have a `Set` type attribute of entity of type `User` and  entity of type `Operator` in contradiction with the definition of a `Set` data type.

Trying to change the schema to:
```
[...],
"Group" : {
    "shape" : {
        "type" : "Record",
        "attributes": {
            "Admins": {
                "type": "Set",
                "element": {
                    "type": "Entity",
                    "name": "User"
                },
                "element": {
                    "type": "Entity",
                    "name": "Operator"
                }
            }
        }
    }
},
[...]
```

Will throw a `Duplicate attribute Element`

Trying to change the schema to:
```
[...],
"Group" : {
    "shape" : {
        "type" : "Record",
        "attributes": {
            "Admins": {
                "type": "Set",
                "element": [
                    {
                        "type": "Entity",
                        "name": "User"
                    },
                    "element": {
                         "type": "Entity",
                         "name": "Operator"
                    }
               ]
            }
        }
    }
},
[...]
```

Will throw a `Undeclared common types: {"Set"}` cause the `Set` definition no longer a natural definition and Cedar tries to find another definition in `commonTypes` which is unsuccessful.

Thoughts?

**Comment by jeffsec-aws** [comment]
> You can store multiple types in a Set, period. Multiple entity types, multiple non-entity types, even mixed (some entity and some non-entity types).

Ok but if I have a Schema defined will it not fail the Schema definition?

> I thought this was clearly documented in our docs, but clearly it is not

The problem is the general sense that it is possible in policies while now I get it is none. See through examples like:
> [false, 3, [47, 0], "some"].containsAll([3, "some"])         // true

or

> [1,"something",2].contains(1)                   // true
[1,"something",2].contains("Something")         // false - string comparison is case-sensitive

the last test seems to mean that the next test would have worked:
> [1,"something",2].contains("something")                   // true

or

> [User::"alice"].contains(principal)             // true if principal == User::"alice"

Which tends to mean that the following would work too:
> > [User::"alice", Operator::"bob", 1, "Something"].contains(principal)             // true if principal == User::"alice"

**Comment by cdisselkoen** [comment]
All of those do work, but policies using those patterns cannot be validated, due to limitations of today's schema format and validator.  The docs should be clearer on this point, I agree.
