### ISSUE TITLE
BatchIsAuthorized() support

### ISSUE THREAD

**Issue by jeffsec-aws** [cedar-policy/rfcs#87]
This API method from Amazon Verified Permissions is super interesting but I don't know if there is a advantage to re implement it at the Cedar Level.

We got a discussion about this on the Cedar Slack workspace: https://cedar-policy.slack.com/archives/C0547KH7R19/p1730466852185509

**Comment by cdisselkoen** [comment]
There is already an issue for this: https://github.com/cedar-policy/cedar/issues/1273

**Comment by jeffsec-aws** [comment]
Missed the referenced issue.
