### ISSUE TITLE
JWT validation and container for principal entity information

### ISSUE THREAD

**Issue by jeffsec-aws** [cedar-policy/rfcs#88]
JSON Web Token as an integrity preserved container to pass information about a principal is becoming a new trend.

https://www.linkedin.com/events/7224508989055676416/comments/

Support of the ability to provide principal entity information through JWT in an isAuthorized() call to the Cedar SDK will offload a lot of the logic from customer hands by:

- Validating the JWT
- Mapping the JWT claim to principal entity attributes
- Evaluating Cedar policy as usual from there

**Comment by adpaco-aws** [comment]
Hey @jeffsec-aws , thanks for requesting this feature! We will review your request and be in touch soon.
